// Do not touch this file. It is generated by Zerve-Sync
// To update the file, modify the zerve field in package.json.zerve and run "npx zerve-sync"

import * as zStoreData from './data-sync.json';
import * as zStoreSchema from './schema-sync.json';
import { createZStoreClient } from '@zerve/client/StoreClient';

const zStoreProtocol = "https://";
const zStoreOrigin = "alpha.zerve.app";
const zStorePath = ".z/store/ev/zerve";


export type BannerFileSchema = string;


export const zClient = createZStoreClient(
  zStoreProtocol,
  zStoreOrigin,
  zStorePath,
  zStoreSchema,
  zStoreData
);

export const zAccessors = {
  Banner: zClient.createAccessor<BannerFileSchema>("Banner"),
}

export const useBanner = zAccessors.Banner.use;

