import { ModuleSpec } from "@zerve/core";
import { readdir, writeFile, readFile } from "fs-extra";
import { join } from "path";

const toolsPackageRoot = process.cwd();
const repoRoot = join(toolsPackageRoot, "../..");
const modulesRoot = join(repoRoot, "packages/modules");
const modulesPackagePath = join(modulesRoot, "package.json");
const modulesIndexTsPath = join(modulesRoot, "index.ts");
const modulesConfigPath = join(modulesRoot, "modules.config.js");

const modulesConfig = require(modulesConfigPath);

function generateIndexTs(moduleSpecs: Record<string, ModuleSpec>) {
  return `// !!! 🛑  DO NOT EDIT THIS FILE BY HAND
// THIS FILE IS GENERATED BY packages/modules-tools/prepareModules.ts

${Object.entries(moduleSpecs)
  .map(([moduleName, moduleSpec]) =>
    moduleSpec.module
      ? `import ${moduleName}Module from "./${join(
          moduleName,
          moduleSpec.module
        )}";`
      : ""
  )
  .join("\n")}

export const AllModules = {
${Object.entries(moduleSpecs)
  .filter(([_moduleName, moduleSpec]) => !!moduleSpec.module)
  .map(([moduleName]) => `  ${moduleName}: ${moduleName}Module,`)
  .join("\n")}
};
    
${Object.entries(moduleSpecs)
  .filter(([_moduleName, moduleSpec]) => !!moduleSpec.module)
  .map(([moduleName]) => `export const ${moduleName} = ${moduleName}Module;`)
  .join("\n")}
    
// Module Specs:
// ${JSON.stringify(moduleSpecs)}

// END AUTO-GENERATED BY packages/modules-tools/prepareModules.ts
`;
}

async function applyFile(filePath: string, fileData: any): Promise<boolean> {
  let prevDataValue = null;
  try {
    prevDataValue = await readFile(filePath, {
      encoding: "utf8",
    });
  } catch (e) {}

  if (fileData !== prevDataValue) {
    await writeFile(filePath, fileData);
    return true;
  }
  return false;
}

export async function prepareModules(includedModules: string[]) {
  const listedModules = await readdir(modulesRoot);

  const { localIncludedModules } = modulesConfig;

  const dependencies: Record<string, string> = {
    "@zerve/core": "*",
  };

  const moduleSpecs = Object.fromEntries(
    await Promise.all(
      localIncludedModules.map(async (moduleName) => {
        try {
          const moduleSpecData = await readFile(
            join(modulesRoot, moduleName, "module.json"),
            { encoding: "utf8" }
          );
          const moduleSpec = JSON.parse(moduleSpecData);
          // todo validate module spec
          return [moduleName, moduleSpec as ModuleSpec];
        } catch (e) {
          console.error(`Failed to read module file of ${moduleName}`);
          return [moduleName, {}];
        }
      })
    )
  );

  Object.entries(moduleSpecs).forEach(
    ([moduleName, moduleSpec]: [string, ModuleSpec]) => {
      if (moduleSpec.npmDependencies) {
        Object.entries(moduleSpec.npmDependencies).map(
          ([npmDepName, npmDepValue]) => {
            const prevDep = dependencies[npmDepName];
            if (prevDep === undefined) {
              dependencies[npmDepName] = npmDepValue;
            } else if (prevDep !== npmDepValue) {
              throw new Error(
                `Unable to handle unmatching npm dependencies of modules. Module "${moduleName}" requires "${npmDepName}"@${npmDepValue} but other modules require ${npmDepName} with version "${prevDep}".`
              );
            } else {
              // dep already set correctly
            }
          }
        );
      }
    }
  );

  const packageJson = {
    "//": "🛑  DO NOT EDIT MANUALLY. FILE GENERATED BY packages/modules-tools/prepareModules.ts",
    name: "@zerve/modules",
    version: "0.0.0",
    private: true,
    dependencies,
    main: "./index.ts",
    types: "./index.ts",
    devDependencies: {
      config: "*",
      tsconfig: "*",
      typescript: "^4.5.5",
    },
  };

  const modulesPkgData = JSON.stringify(packageJson, null, 2);
  const hasAppliedModule = await applyFile(modulesPackagePath, modulesPkgData);
  const hasAppliedIndexTs = await applyFile(
    modulesIndexTsPath,
    generateIndexTs(moduleSpecs)
  );

  if (hasAppliedModule)
    console.log(
      "🟢 Modules package.json written successfully. 🛑 Re-run yarn to install module dependencies! 🛑"
    );
  if (hasAppliedIndexTs)
    console.log("🟢 Modules index.ts written successfully.");

  if (hasAppliedModule) {
    throw new Error("🛑 Re-run yarn to install module dependencies");
  }

  console.log("✅ Modules are configured correctly.");
}

prepareModules([])
  .then(() => {
    // console.log("done.");
  })
  .catch((e) => {
    console.error(e);
  });
