// Do not touch this file. It is generated by Zerve-Sync
// To update the file, modify the zerve field in package.json.zerve and run "npx zerve-sync"

import * as zStoreData from "./data-sync.json";
import * as zStoreSchema from "./schema-sync.json";
import { createZStoreClient } from "@zerve/client/StoreClient";
import { FromSchema, JSONSchema7 } from "json-schema-to-ts";

const zStoreProtocol = "http://";
const zStoreOrigin = "localhost:3988";
const zStorePath = "Zerve";

const zClient = createZStoreClient(
  zStoreProtocol,
  zStoreOrigin,
  zStorePath,
  zStoreSchema,
  zStoreData
);

export const test = zClient.createAccessor("test", {
  type: "null",
});
export const newfilename = zClient.createAccessor("newfilename", {
  type: "array",
});
export const t = zClient.createAccessor("t", {
  $ref: "https://type.zerve.link/ayo",
  title: "ayo",
});
export const AllowNewUsers = zClient.createAccessor("AllowNewUsers", {
  default: false,
  description: "",
  title: "",
  type: "boolean",
});

export const FF = zClient.createAccessor("FF");
