
// Do not touch this file. It is generated by Zerve-Sync
// To update the file, modify the zerve field in package.json.zerve and run "npx zerve-sync"

import * as zStoreData from './data-sync.json';
import * as zStoreSchema from './schema-sync.json';
import { createZStoreClient } from '@zerve/client/StoreClient';

const zStoreProtocol = "http://";
const zStoreOrigin = "localhost:3988";
const zStorePath = "Zerve";

export interface Ayo {
  [k: string]: number;
}

export type TestFileSchema = null;

export type NewfilenameFileSchema = unknown[];

export type TFileSchema = Ayo[];

export type AllowNewUsersFileSchema = boolean;


export const zClient = createZStoreClient(
  zStoreProtocol,
  zStoreOrigin,
  zStorePath,
  zStoreSchema,
  zStoreData
);

export const test = zClient.createAccessor<TestFileSchema>("test");
export const newfilename = zClient.createAccessor<NewfilenameFileSchema>("newfilename");
export const t = zClient.createAccessor<TFileSchema>("t");
export const AllowNewUsers = zClient.createAccessor<AllowNewUsersFileSchema>("AllowNewUsers");

