// !!! 🛑  DO NOT EDIT THIS FILE BY HAND
// THIS FILE IS GENERATED BY packages/modules-tools/prepareModules.ts

import { defineModule } from "@zerve/core";




const CoreData = defineModule(
  "CoreData",
  {},
  { schema: { type: "null" } as const },
  {},
);

export default CoreData;

// END AUTO-GENERATED BY packages/modules-tools/prepareModules.ts
