// !!! 🛑  DO NOT EDIT THIS FILE BY HAND
// THIS FILE IS GENERATED BY packages/modules-tools/prepareModules.ts

import AuthModule from "./Auth/Auth";
import CoreChainModule from "./CoreChain/CoreChain";
import CoreDataModule from "./CoreData/CoreData";
import CoreStoreModule from "./CoreStore/CoreStore";
import LedgerModule from "./Ledger/Ledger";
import MessageEmailModule from "./MessageEmail/MessageEmail";
import MessageSMSModule from "./MessageSMS/MessageSMS";
import OBSModule from "./OBS/OBS";


import SampleCalculatorModule from "./SampleCalculator/SampleCalculator";
import SystemCaddyModule from "./SystemCaddy/SystemCaddy";
import SystemCommandsModule from "./SystemCommands/SystemCommands";
import SystemFetchModule from "./SystemFetch/SystemFetch";
import SystemFilesModule from "./SystemFiles/SystemFiles";
import SystemSSHModule from "./SystemSSH/SystemSSH";

export const AllModules = {
  Auth: AuthModule,
  CoreChain: CoreChainModule,
  CoreData: CoreDataModule,
  CoreStore: CoreStoreModule,
  Ledger: LedgerModule,
  MessageEmail: MessageEmailModule,
  MessageSMS: MessageSMSModule,
  OBS: OBSModule,
  SampleCalculator: SampleCalculatorModule,
  SystemCaddy: SystemCaddyModule,
  SystemCommands: SystemCommandsModule,
  SystemFetch: SystemFetchModule,
  SystemFiles: SystemFilesModule,
  SystemSSH: SystemSSHModule,
};
    
export const Auth = AuthModule;
export const CoreChain = CoreChainModule;
export const CoreData = CoreDataModule;
export const CoreStore = CoreStoreModule;
export const Ledger = LedgerModule;
export const MessageEmail = MessageEmailModule;
export const MessageSMS = MessageSMSModule;
export const OBS = OBSModule;
export const SampleCalculator = SampleCalculatorModule;
export const SystemCaddy = SystemCaddyModule;
export const SystemCommands = SystemCommandsModule;
export const SystemFetch = SystemFetchModule;
export const SystemFiles = SystemFilesModule;
export const SystemSSH = SystemSSHModule;
    
// Module Specs:
// {"Auth":{"module":"./Auth"},"CoreChain":{"module":"./CoreChain","npmDependencies":{"@zerve/crypto":"*"}},"CoreData":{"module":"./CoreData","npmDependencies":{"@zerve/crypto":"*"}},"CoreStore":{"module":"./CoreStore","npmDependencies":{"@zerve/crypto":"*"}},"Ledger":{"module":"./Ledger"},"MessageEmail":{"module":"./MessageEmail","npmDependencies":{"@sendgrid/mail":"*"}},"MessageSMS":{"module":"./MessageSMS","npmDependencies":{"axios":"*"}},"OBS":{"module":"./OBS","npmDependencies":{"obs-websocket-js":"^4.0.3"}},"ProviderCloudFlare":{},"ProviderDigitalOcean":{},"SampleCalculator":{"module":"./SampleCalculator"},"SystemCaddy":{"module":"./SystemCaddy"},"SystemCommands":{"module":"./SystemCommands"},"SystemFetch":{"module":"./SystemFetch"},"SystemFiles":{"module":"./SystemFiles","npmDependencies":{"fs-extra":"*"}},"SystemSSH":{"module":"./SystemSSH","npmDependencies":{"ssh-config":"4.x.x"}}}

// END AUTO-GENERATED BY packages/modules-tools/prepareModules.ts
