// !!! 🛑  DO NOT EDIT THIS FILE BY HAND
// THIS FILE IS GENERATED BY packages/modules-tools/prepareModules.ts



import OBSModule from "./OBS/OBS";
import SampleCalculatorModule from "./SampleCalculator/SampleCalculator";
import SystemCaddyModule from "./SystemCaddy/SystemCaddy";
import SystemFilesModule from "./SystemFiles/SystemFiles";
import SystemShellModule from "./SystemShell/SystemShell";

export const AllModules = {
  OBS: OBSModule,
  SampleCalculator: SampleCalculatorModule,
  SystemCaddy: SystemCaddyModule,
  SystemFiles: SystemFilesModule,
  SystemShell: SystemShellModule,
};
    
export const OBS = OBSModule;
export const SampleCalculator = SampleCalculatorModule;
export const SystemCaddy = SystemCaddyModule;
export const SystemFiles = SystemFilesModule;
export const SystemShell = SystemShellModule;
    
// Module Specs:
// {"Auth":{},"CoreData":{},"OBS":{"module":"./OBS","npmDependencies":{"obs-websocket-js":"^4.0.3"}},"SampleCalculator":{"module":"./SampleCalculator"},"SystemCaddy":{"module":"./SystemCaddy"},"SystemFiles":{"module":"./SystemFiles","npmDependencies":{"fs-extra":"*"}},"SystemShell":{"module":"./SystemShell"}}

// END AUTO-GENERATED BY packages/modules-tools/prepareModules.ts
