// !!! 🛑  DO NOT EDIT THIS FILE BY HAND
// THIS FILE IS GENERATED BY packages/modules-tools/prepareModules.ts

import { defineModule } from "@zerve/core";

import SampleCalculatorState from "./SampleCalculator.state";
import SampleCalculatorActions from "./SampleCalculator.actions";

const SampleCalculator = defineModule(
  "SampleCalculator",
  {"actions":"./SampleCalculator.actions","state":"./SampleCalculator.state"},
  SampleCalculatorState,
  SampleCalculatorActions,
);

export default SampleCalculator;

// END AUTO-GENERATED BY packages/modules-tools/prepareModules.ts
