// !!! 🛑  DO NOT EDIT THIS FILE BY HAND
// THIS FILE IS GENERATED BY packages/modules-tools/prepareModules.ts

import { defineModule } from "@zerve/core";


import OBSActions from "./OBS.actions";

const OBS = defineModule(
  "OBS",
  {"actions":"./OBS.actions","npmDependencies":{"obs-websocket-js":"^4.0.3"}},
  { schema: { type: "null" } as const },
  OBSActions,
);

export default OBS;

// END AUTO-GENERATED BY packages/modules-tools/prepareModules.ts
