// !!! 🛑  DO NOT EDIT THIS FILE BY HAND
// THIS FILE IS GENERATED BY packages/modules-tools/prepareModules.ts

import { defineModule } from "@zerve/core";




const SystemShell = defineModule(
  "SystemShell",
  {},
  { schema: { type: "null" } as const },
  {},
);

export default SystemShell;

// END AUTO-GENERATED BY packages/modules-tools/prepareModules.ts
