// Do not touch this file. It is generated by Zerve-Sync
// To update the file, modify the zerve field in package.json.zerve and run "npx zerve-sync"

import * as zStoreData from './data-sync.json';
import * as zStoreSchema from './schema-sync.json';
import { createZStoreClient } from '@zerve/client/StoreClient';

const zStoreProtocol = "https://";
const zStoreOrigin = "staging.zerve.dev";
const zStorePath = ".z/Store/ev/demo";

export interface QuestionAnswer {
  Answer?: string;
  Question?: string;
}

export type FAQEntriesFileSchema = QuestionAnswer[];

export type BigQuestionFileSchema = QuestionAnswer;
export type FFileSchema = null;


export const zClient = createZStoreClient(
  zStoreProtocol,
  zStoreOrigin,
  zStorePath,
  zStoreSchema,
  zStoreData
);

export const zAccessors = {
  FAQEntries: zClient.createAccessor<FAQEntriesFileSchema>("FAQEntries"),
  BigQuestion: zClient.createAccessor<BigQuestionFileSchema>("BigQuestion"),
  F: zClient.createAccessor<FFileSchema>("f"),
}

export const useFAQEntries = zAccessors.FAQEntries.use;
export const useBigQuestion = zAccessors.BigQuestion.use;
export const useF = zAccessors.F.use;

