// !!! 🛑  DO NOT EDIT THIS FILE BY HAND
// THIS FILE IS GENERATED BY packages/modules-tools/prepareModules.ts

import { defineModule } from "@zerve/core";




const Auth = defineModule(
  "Auth",
  {},
  { schema: { type: "null" } as const },
  {},
);

export default Auth;

// END AUTO-GENERATED BY packages/modules-tools/prepareModules.ts
