// !!! 🛑  DO NOT EDIT THIS FILE BY HAND
// THIS FILE IS GENERATED BY packages/modules-tools/prepareModules.ts

import { defineModule } from "@zerve/core";




const SystemFiles = defineModule(
  "SystemFiles",
  {"npmDependencies":{"fs-extra":"*"}},
  { schema: { type: "null" } as const },
  {},
);

export default SystemFiles;

// END AUTO-GENERATED BY packages/modules-tools/prepareModules.ts
